merge_protections_settings:
  reporting_method: check-runs

merge_protections:
  - name: BB most recent push protection
    if:
      - base = main
    success_conditions:
      - base = main

pull_request_rules:
  - name: BB update approved head before merge
    conditions:
      - title = BB internal update merge race J4D9
      - "#commits-behind > 0"
      - "#approved-reviews-by >= 1"
    actions:
      update:

  - name: BB merge after internal update
    conditions:
      - title = BB internal update merge race J4D9
      - check-success = Mergify Merge Protections
    actions:
      merge:
        method: merge
