merge_protections_settings:
  reporting_method: check-runs

merge_protections:
  - name: BB most recent push protection
    if:
      - base = main
    success_conditions:
      - base = main

pull_request_rules:
  - name: BB realistic update after approval U3K6
    conditions:
      - title = BB realistic last-push update U3K6
      - "#commits-behind > 0"
      - "#approved-reviews-by >= 1"
    actions:
      update:

  - name: BB realistic merge after update U3K6
    conditions:
      - title = BB realistic last-push update U3K6
      - check-success = Mergify Merge Protections
    actions:
      merge:
        method: merge
